name: Checks

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  typos:
    name: check misspelling by typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Run typos command
        shell: nix shell nixpkgs#typos --quiet --command bash {0}
        run: typos --hidden --exclude .git --format brief

  cocogitto:
    name: check conventional commits
    runs-on: ubuntu-latest
    # Only run this step in the main branch.
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Check the latest commit message
        shell: nix shell nixpkgs#cocogitto --quiet --command bash {0}
        run: cog check HEAD..HEAD

  rumdl:
    name: lint markdown by rumdl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Run rumdl command
        shell: nix shell nixpkgs#rumdl --quiet --command bash {0}
        run: rumdl check .

  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Run nix command
        run: nix flake check --all-systems

  nixfmt-check:
    name: nixfmt check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Run nix command
        shell: nix shell nixpkgs#nixfmt-rs --quiet --command bash {0}
        run: nixfmt --check .

  trivy-scan:
    name: use trivy to scan files
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Run Trivy vulnerability scanner in repo mode
        shell: nix shell nixpkgs#trivy --quiet --command bash {0}
        run: |
          trivy --quiet fs . \
            --output trivy-fs-results.sarif \
            --severity CRITICAL,HIGH,MEDIUM \
            --skip-dirs ./target \
            --format sarif \
            --exit-code 1
          trivy --quiet config . \
            --output trivy-config-results.sarif \
            --severity CRITICAL,HIGH,MEDIUM \
            --skip-dirs ./target \
            --format sarif \
            --exit-code 1
      - name: Upload "trivy fs" results to GitHub Security tab
        if: ${{ success() || failure() }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-fs-results.sarif
          category: trivy-fs-scan
      - name: Upload "trivy config" results to GitHub Security tab
        if: ${{ success() || failure() }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-config-results.sarif
          category: trivy-config-scan
